name: NxCache
permissions:
   contents: read
   actions: write
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      # Set up a matrix to run the following 3 configurations:
      # 1. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 2. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 3. <MacOS, Release, latest Clang compiler toolchain on the default runner image, default generator>
      matrix:
        os: [ubuntu, windows, macos]

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      VCPKG_BINARY_SOURCES: 'clear;files,${{ github.workspace }}/vcpkg_cache,readwrite'

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Create cache directory
      run: mkdir -p ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}

    - name: Restore cache
      uses: actions/cache@v5
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ matrix.os }}-${{ hashFiles('vcpkg.json') }}-${{ hashFiles('vcpkg-configuration.json') }}
        restore-keys: ${{ matrix.os }}-

    - name: Set up vcpkg root
      shell: bash
      run: |
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

    - name: Configure
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C Release --output-on-failure

    - name: Package
      if: matrix.os == 'ubuntu'
      working-directory: ${{ github.workspace }}/build
      run: cpack -G DEB

    - name: Install
      working-directory: ${{ github.workspace }}/build
      run: cmake --install . --config Release --prefix ${{ github.workspace }}/out

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nxcache-${{ matrix.os }}
        path: ${{ github.workspace }}/out/

    - name: Upload package
      if: matrix.os == 'ubuntu'
      uses: actions/upload-artifact@v4
      with:
        name: nxcache-deb
        path: ${{ github.workspace }}/build/*.deb
